# Generated by Django 4.1.7 on 2023-03-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0009_brocamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brocamp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
