# Generated by Django 4.1.7 on 2023-04-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0011_student_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
